### ISSUE TITLE
Q: smoothness, and paper link

### ISSUE THREAD

**Issue by thorade** [sakov/csa-c#2]
This is just a question, sorry for posting as issue: Could you update the link to the paper, and possibly already state the title in the readme, so it could also be found using Google?
What I hope to learn from the paper is how smooth the interpolation is, I am looking for an opensource library that can do C2 smooth interpolation, and has an interface that allows to get the value, first and second derivative for a given point in one call.
Any feedback welcome, I am still learning about the various interpolation methods.

**Comment by sakov** [comment]
Hi thorade, thanks for letting me know that the reference is no longer valid. I updated it to a DOI address, and quoted some text from the paper for a short description.
